### PR TITLE
Refactor phone to description

### LINKED ISSUE #26: Refactor Phone class to Description class

### PR DESCRIPTION
**Pull request by hengyongming**
Fixed #26

### CODE REVIEW

**Review by noelmathewisaac — COMMENTED** [review]
Some tests are failing, try running tests locally to see whats happening

**Comment by hengyongming** [comment]
> Some tests are failing, try running tests locally to see whats happening

Yep, I have fixed the error

**Review by noelmathewisaac — APPROVED** [review]
LGTM

**Review by khiaxeng — APPROVED** [review]
LGTM
Edit: Accidentally closed issue without merging, will merge once the checks are done.
Edit2: Merged branch.

**Pull request merged**
