### PR TITLE
DG updates

### PR DESCRIPTION
**Pull request by hengyongming**
Updated Target User Profile, User Stories, Non-Functional Requirements of DG

### CODE REVIEW

**Review by noelmathewisaac — COMMENTED** [review]
Should we keep the rest other parts of the DG or delete them since it pertains to AB3?

**Comment by hengyongming** [comment]
> Should we keep the rest other parts of the DG or delete them since it pertains to AB3?

I think we can just leave it in the meantime and remove it progressively in the future.

**Review by noelmathewisaac — APPROVED** [review]
LGTM

**Review by khiaxeng — APPROVED** [review]
LGTM

**Pull request merged**
