### PR TITLE
Update DG - Implementation for the 3 new delete multiple features + Glossary

### LINKED ISSUE #51: Update DG

### PR DESCRIPTION
**Pull request by CSmortal**
For glossary, we cn just all update when we doing our part for DG

### CODE REVIEW

**Comment by CSmortal** [comment]
7.4 Manual testing for delete doesnt seem to be adequate

**Comment by noelmathewisaac** [comment]
> 7.4 Manual testing for delete doesnt seem to be adequate

Didn't add much for the delete section. The manual testing is just a starting guide though. Maybe you can add if you have time

**Review by hengyongming — APPROVED** [review]
Looks good

**Review by noelmathewisaac — APPROVED** [review]
LGTM

**Pull request merged**
