### PR TITLE
Added sort by deadline functionality

### LINKED ISSUE #8: View Task Deadlines
As a university student, I can modify the view deadline of tasks so that I can do tasks that are more urgent.

### PR DESCRIPTION
**Pull request by hengyongming**
Closes #8

### CODE REVIEW

**Review by CSmortal — COMMENTED** [review]
would be good to test if the list of tasks is sorted after reopening the app

**Comment by hengyongming** [comment]
> would be good to test if the list of tasks is sorted after reopening the app

I think it is. However, you will need to use the exit command so that the storage saved the latest updated task list

**Comment by CSmortal** [comment]
> I think it is. However, you will need to use the exit command so that the storage saved the latest updated task list

I'm not entirely sure, but i dont think we need to use exit command? For the test, can't we just instantiate a new TaskifyStub and then check if its tasks are sorted?

**Comment by noelmathewisaac** [comment]
> > would be good to test if the list of tasks is sorted after reopening the app
> 
> I think it is. However, you will need to use the exit command so that the storage saved the latest updated task list

If its too much trouble to use the exit function then just writing unit tests to see if the sorting logic works correctly would be good.

**Review by khiaxeng — APPROVED** [review]
LGTM

**Review by noelmathewisaac — APPROVED** [review]
LGTM, tests can be added later

**Pull request merged**
